# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# C++ -- may need 

# DEPENDENCIES:
#   - C++11
#   - clang4.0 (nonstandard version for OpenMP support(-fopenmp), necessary?)
#   - R 3.4.3
#
#   - R packages (defined in DESCRIPTION)
#     - RInside (development version via GitHub)
#     - Rcpp (CRAN)
#     - RcppArmadillo (CRAN)
#     # Header

language: r
sudo: false
dist: trusty
cache: packages
latex: false

# For coverate reporting
r_packages:
  - covr

# Build project
script:
  - make

# Report coverage rate to coveralls
after_success:
    - Rscript -e 'library(covr); codecov()'

# Send e-mails if stuff changes
notifications:
  email:
    on_success: change
    on_failure: change


