# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# C++ -- may need 

# DEPENDENCIES:
#   - C++11
#   - clang4.0 (nonstandard version for OpenMP support(-fopenmp), necessary?)
#   - R 3.4.3
#
#   - R packages (defined in DESCRIPTION)
#     - RInside (development version via GitHub)
#     - Rcpp (CRAN)
#     - RcppArmadillo (CRAN)
#     # Header

language: r
sudo: false
dist: trusty
cache: packages
latex: false
r_packages:
  - covr

# build project
script:
  - make
  - ./get_code_cov.sh
  - codecov

# send e-mails if stuff changes
notifications:
  email:
    on_success: change
    on_failure: change


