# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Joint Single Subject Model
#'
#' Fit a joint Bayesian model for two coupled pulsatile hormones measured
#' from a single subject. Driver pulses influence response pulse occurrence
#' through a coupling kernel parameterized by rho and nu.
#'
#' @param driver_concentration Numeric vector of driver hormone concentrations
#' @param driver_time Numeric vector of driver hormone measurement times
#' @param response_concentration Numeric vector of response hormone concentrations
#' @param response_time Numeric vector of response hormone measurement times
#' @param location_prior Character string: "strauss" (only option currently)
#' @param driver_priors List of prior parameters for driver hormone
#' @param response_priors List of prior parameters for response hormone
#' @param association_priors List of prior parameters for coupling (rho, nu)
#' @param proposalvars List of proposal variances for all parameters
#' @param driver_startingvals List of starting values for driver parameters
#' @param response_startingvals List of starting values for response parameters
#' @param association_startingvals List of starting values for coupling parameters
#' @param mcmc_iterations Integer: total MCMC iterations to run
#' @param thin Integer: thinning interval for saving samples
#' @param burnin Integer: number of initial iterations to discard
#' @param verbose Logical: print progress messages
#' @param pv_adjust_iter Integer: interval for proposal variance adaptation
#' @param pv_adjust_max_iter Integer: iteration to stop adaptation
#' @param bivariate_pv_target_ratio Numeric: target acceptance rate for bivariate proposals
#' @param univariate_pv_target_ratio Numeric: target acceptance rate for univariate proposals
#'
#' @return List containing MCMC chains for driver, response, and association parameters
#' @export
jointsinglesubject_ <- function(driver_concentration, driver_time, response_concentration, response_time, location_prior, driver_priors, response_priors, association_priors, proposalvars, driver_startingvals, response_startingvals, association_startingvals, mcmc_iterations, thin, burnin, verbose, pv_adjust_iter, pv_adjust_max_iter, bivariate_pv_target_ratio, univariate_pv_target_ratio) {
    .Call(`_bayespulse_jointsinglesubject_`, driver_concentration, driver_time, response_concentration, response_time, location_prior, driver_priors, response_priors, association_priors, proposalvars, driver_startingvals, response_startingvals, association_startingvals, mcmc_iterations, thin, burnin, verbose, pv_adjust_iter, pv_adjust_max_iter, bivariate_pv_target_ratio, univariate_pv_target_ratio)
}

population_ <- function(subject_data_list, location_prior, population_priors, proposalvars, population_startingvals, subject_startingvals_list, mcmc_iterations, thin, burnin, verbose, pv_adjust_iter, pv_adjust_max_iter, bivariate_pv_target_ratio, univariate_pv_target_ratio) {
    .Call(`_bayespulse_population_`, subject_data_list, location_prior, population_priors, proposalvars, population_startingvals, subject_startingvals_list, mcmc_iterations, thin, burnin, verbose, pv_adjust_iter, pv_adjust_max_iter, bivariate_pv_target_ratio, univariate_pv_target_ratio)
}

singlesubject_ <- function(concentration, time, location_prior, inpriors, proposalvars, startingvals, mcmc_iterations, thin, burnin, verbose, pv_adjust_iter, pv_adjust_max_iter, bivariate_pv_target_ratio, univariate_pv_target_ratio) {
    .Call(`_bayespulse_singlesubject_`, concentration, time, location_prior, inpriors, proposalvars, startingvals, mcmc_iterations, thin, burnin, verbose, pv_adjust_iter, pv_adjust_max_iter, bivariate_pv_target_ratio, univariate_pv_target_ratio)
}

