// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// RcppGibbs
NumericMatrix RcppGibbs(int n, int thn);
RcppExport SEXP _poppulsatile_RcppGibbs(SEXP nSEXP, SEXP thnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type thn(thnSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGibbs(n, thn));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests();

static const R_CallMethodDef CallEntries[] = {
    {"_poppulsatile_RcppGibbs", (DL_FUNC) &_poppulsatile_RcppGibbs, 2},
    {"run_testthat_tests",      (DL_FUNC) &run_testthat_tests,      0},
    {NULL, NULL, 0}
};

RcppExport void R_init_poppulsatile(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
