# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

population_ <- function(concentrations, times, location_prior, inpriors, proposalvars, startingvals, mcmc_iterations, thin, burnin, verbose, verbose_patient, verbose_iter, pv_adjust_iter, pv_adjust_max_iter, bivariate_pv_target_ratio, univariate_pv_target_ratio, fix_params, pat_mass_mean_vec, pat_width_mean_vec, pat_baseline_vec, pat_halflife_vec, pulse_count_vec, masses_vec, width_vec, mass_sdscale_vec, width_sdscale_vec, location_vec) {
    .Call(`_bayespulse_population_`, concentrations, times, location_prior, inpriors, proposalvars, startingvals, mcmc_iterations, thin, burnin, verbose, verbose_patient, verbose_iter, pv_adjust_iter, pv_adjust_max_iter, bivariate_pv_target_ratio, univariate_pv_target_ratio, fix_params, pat_mass_mean_vec, pat_width_mean_vec, pat_baseline_vec, pat_halflife_vec, pulse_count_vec, masses_vec, width_vec, mass_sdscale_vec, width_sdscale_vec, location_vec)
}

singlesubject_ <- function(concentration, time, location_prior, inpriors, proposalvars, startingvals, mcmc_iterations, thin, burnin, verbose, verbose_iter, pv_adjust_iter, pv_adjust_max_iter, bivariate_pv_target_ratio, univariate_pv_target_ratio, fix_params, masses_vec, width_vec, mass_tvarscale_vec, width_tvarscale_vec, location_vec) {
    .Call(`_bayespulse_singlesubject_`, concentration, time, location_prior, inpriors, proposalvars, startingvals, mcmc_iterations, thin, burnin, verbose, verbose_iter, pv_adjust_iter, pv_adjust_max_iter, bivariate_pv_target_ratio, univariate_pv_target_ratio, fix_params, masses_vec, width_vec, mass_tvarscale_vec, width_tvarscale_vec, location_vec)
}

