# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hello world using Rcpp
#' 
#' Simple function using Rcpp
#' 
#' @alias rcpp_hello_world
#' 
#' @examples
#' \dontrun{
#' rcpp_hello_world()
#' }
#' @useDynLib poppulsatile, .registration=TRUE)
#' @export
rcpp_hello_world <- function() {
    .Call(`_poppulsatile_rcpp_hello_world`)
}

